# -*- coding: utf-8 -*-
"""stage1_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/palak348/Smart-glasses/blob/main/notebooks/stage1_detection.ipynb

# BCG Stage 1 — Step A: Object Detection (stock YOLO26 Nano)

First milestone of the phone-side AI pipeline: run **stock YOLO26 Nano** on an image and see what it detects.

- Runs on Colab (set Runtime → Change runtime type → **T4 GPU**).
- This is just the detection step — depth, zone logic, and audio come later.
- Run each cell with **Shift + Enter**.

### 1. Install Ultralytics (YOLO library)
"""

!pip install ultralytics

"""### 2. Load the model and run detection

`yolo26n.pt` auto-downloads the first time. `conf=0.4` keeps only detections the model is at least 40% confident about.
"""

from ultralytics import YOLO

# Stock YOLO26 Nano — pre-trained on COCO (80 common classes).
model = YOLO("yolo26n.pt")

# Run on a demo image that ships with Ultralytics (a bus + people).
results = model("https://ultralytics.com/images/bus.jpg", conf=0.4)
result = results[0]

# Stage-1 output = a simple text log of what was detected.
for box in result.boxes:
    label = model.names[int(box.cls)]
    print(f"Detected: {label}  ({float(box.conf):.2f})")

"""### 3. Show the image with boxes drawn"""

import matplotlib.pyplot as plt

# result.plot() returns the image with boxes drawn (in BGR); flip to RGB to show.
annotated = result.plot()
plt.figure(figsize=(8, 8))
plt.imshow(annotated[..., ::-1])
plt.axis("off")
plt.show()

from google.colab import files
uploaded = files.upload()        # picker me saari 16 select karo (Ctrl+click)
print(f"\n{len(uploaded)} images uploaded")

import cv2, matplotlib.pyplot as plt

for img_name in uploaded.keys():
    img = cv2.imread(img_name)
    r_hd   = model(img, conf=0.4)[0]
    r_qvga = model(cv2.resize(img, (320, 240)), conf=0.4)[0]

    print(f"\n=== {img_name} ===")
    print("HIGH-RES :", [model.names[int(b.cls)] for b in r_hd.boxes])
    print("QVGA     :", [model.names[int(b.cls)] for b in r_qvga.boxes])

    fig, ax = plt.subplots(1, 2, figsize=(14, 6))
    ax[0].imshow(r_hd.plot()[..., ::-1]);   ax[0].set_title(f"{img_name} - High-res"); ax[0].axis("off")
    ax[1].imshow(r_qvga.plot()[..., ::-1]); ax[1].set_title("QVGA (glasses)");          ax[1].axis("off")
    plt.show()

